### ISSUE TITLE
CONVERSIONES DE SISTEMAS NUMERICOS”Irwing sael equipo

### ISSUE THREAD

**Issue by irwingsael** [SistemasTecTlaxiaco/actividad-2-ejercicios-team-sael-1as#1]
[CONVERSIÓNES(e).pdf](https://github.com/user-attachments/files/16859870/CONVERSIONES.e.pdf)

**Comment by Johnc-byte** [comment]
portada: 25
Procedimiento:17
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la práctica: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
