### ISSUE TITLE
operaciones de conjuntos

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/actividad-2-ejercicios-team-sael-1as#3]
[OPeraciones de conJUNTOS1 (1).pdf](https://github.com/user-attachments/files/17150123/OPeraciones.de.conJUNTOS1.1.pdf)

**Comment by YulianaMorales18** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 23/25
Resultados y conclusiones 25/25
Calificación: 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
